### ISSUE TITLE
simple-landing-zone not deploying 10.2 spoke vnet

### ISSUE THREAD

**Issue by larryclaman** [mattfeltonma/azure-labs#29]
tried deploying but it did not create the spoke vnet

**Comment by mattfeltonma** [comment]
Really weird. I deployed just last night and it fully deployed without any issue including the spoke virtual network. I'd recommend reviewing your deployment logs to see if you ran into a failure.

**Comment by mattfeltonma** [comment]
Confirmed with @larryclaman it was just a delay in the Portal displaying the resources.
